export const environment = {
  ROOT_URL: 'http://localhost:4200/api/v1',
  SIGN_IN_URL: 'http://localhost:4200/api/v1/auth/sign-in',
  STUDENT_REGISTRATION_URL: 'http://localhost:4200/api/v1/auth/sign-up/student',
  STUDENT_REGISTRATION_OPTIONS_URL: 'http://localhost:4200/api/v1/auth/sign-up/student/options',
  TEACHER_REGISTRATION_URL: 'http://localhost:4200/api/v1/auth/sign-up/teacher',
  LESSONS_URL: 'http://localhost:4200/api/v1/lessons',
  LESSONS_OPTIONS_URL: 'http://localhost:4200/api/v1/lessons/options',
  LESSON_PROGRESS_ME_URL: 'http://localhost:4200/api/v1/progress/me',
  LESSON_PROGRESS_URL: 'http://localhost:4200/api/v1/progress',
  COURSES_URL: 'http://localhost:4200/api/v1/courses',
  OWNED_COURSES_URL: 'http://localhost:4200/api/v1/courses/own',
  STREAM_ENROLLMENT_URL: 'http://localhost:4200/api/v1/enrollments/stream',
  STREAMS_URL: 'http://localhost:4200/api/v1/streams',
  STUDENTS_URL: 'http://localhost:4200/api/v1/students',
  GROUP_ENROLLMENT_URL: 'http://localhost:4200/api/v1/enrollments/group',
  GROUP_OPTIONS_URL: 'http://localhost:4200/api/v1/groups/options',
  GROUP_URL: 'http://localhost:4200/api/v1/groups',
  STUDENT_ENROLLMENT_URL: 'http://localhost:4200/api/v1/enrollments/student',
  ENROLLMENT_OPTIONS_URL: 'http://localhost:4200/api/v1/enrollments/options',
  STUDENT_ME_URL: 'http://localhost:4200/api/v1/auth/students/me',
  TEACHER_ME_URL: 'http://localhost:4200/api/v1/auth/teachers/me',
  TOKEN_KEY: 'jwt',
  EXP_DATE_KEY: 'expiresIn',
  CLIENT_DOMAIN: 'http://localhost:4200',
  BACKEND_DOMAIN: 'http://localhost:8080',
  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_ANONYMOUS: 'ROLE_ANONYMOUS',
  ROLE_TEACHER: 'ROLE_TEACHER',
  ROLE_STUDENT: 'ROLE_STUDENT',
}

